### ISSUE TITLE
代码不全

### ISSUE THREAD

**Issue by ColorfulCoco** [Li-Z-Q/StructRAG#1]
这个文件夹prompts没有，这些construction_graph.txt、routing.txt等能不能提供一下。谢谢

**Comment by Li-Z-Q** [comment]
最终版本的代码我还没有整理好，您提到的这一部分我会尽快补充上去

> 这个文件夹prompts没有，这些construction_graph.txt、routing.txt等能不能提供一下。谢谢

**Comment by ColorfulCoco** [comment]
谢谢

**Comment by zhiiuuu** [comment]
留个脚印

**Comment by gjt-dream** [comment]
请问能否提供这个文件“./Loong/data/loong_process.jsonl”，这个文件只是一个普通的json就行，还是对其内容有要求

**Comment by gjt-dream** [comment]
您好，能不能提供“loong_process.jsonl”这个文件，谢谢

**Comment by Li-Z-Q** [comment]
I add prompts and Loong data, and results file. 
<img width="896" alt="image" src="https://github.com/user-attachments/assets/c4b0e8af-a85c-452c-b5b2-2877116bb709">

The final, organized version of the completed code (StructRAG framework + Router training) will be released after the paper is officially accepted.

**Comment by Li-Z-Q** [comment]
> 您好，能不能提供“loong_process.jsonl”这个文件，谢谢

已添加，感谢提醒
