### ISSUE TITLE
拆分报错

### ISSUE THREAD

**Issue by gjt-dream** [Li-Z-Q/StructRAG#2]
你好，在执行这个方法时structurizer.split_content_and_tile(data['docs'])，会出现错误，data['docs']是一个长串，在使用这个方法是会出现“(print in main.py) Error: list index out of range”。所以我想请问一下，data['docs']的类型是什么，数组吗

**Comment by Li-Z-Q** [comment]
> 你好，在执行这个方法时structurizer.split_content_and_tile(data['docs'])，会出现错误，data['docs']是一个长串，在使用这个方法是会出现“(print in main.py) Error: list index out of range”。所以我想请问一下，data['docs']的类型是什么，数组吗

你好，本仓库的代码正在整理过程中，因此可能会存在运行Bug。                          
如果您希望执行我们的代码，您可以去这里下载：https://drive.google.com/file/d/1T5_8eIJwrQUmXlQTHUbqzY2lhTjkdSor/view?usp=drive_link，  这里是我们实验时的代码，比较混乱，但是能够确保成功执行。

**Comment by gjt-dream** [comment]
> > 你好，在执行这个方法时structurizer.split_content_and_tile（data['docs']），会出现错误，data['docs']是一个长串，在使用这个方法是会出现“（print in main.py） Error： list index out of range”。所以我想请问一下，data['docs']的类型是什么，数组吗
> 
> 你好，本仓库的代码正在整理过程中，因此可能会存在运行Bug。 如果您希望执行我们的代码，您可以去这里下载：[https://drive.google.com/file/d/1T5_8eIJwrQUmXlQTHUbqzY2lhTjkdSor/view?usp=drive_link，](https://drive.google.com/file/d/1T5_8eIJwrQUmXlQTHUbqzY2lhTjkdSor/view?usp=drive_link%EF%BC%8C) 这里是我们实验时的代码，比较混乱，但是能够确保成功执行。

好的，非常感谢
