### ISSUE TITLE
Questions about structured knowledge

### ISSUE THREAD

**Issue by Z-ZHHH** [Li-Z-Q/StructRAG#4]
1. Document preprocessing and query matching:
* Should the algorithm determine data types and structurize all documents before processing each query? The main paper appears to omit details about raw document selection.
* If preprocessing all documents isn't necessary, what's the optimal strategy for selecting query-relevant documents? Should document core content be the primary matching criteria?
2. Large Excel document processing:
* Given that Excel files are essentially tabular data, what are the recommended strategies for handling Excel documents exceeding 100K tokens? 
* Is treating it as a single large table the optimal approach, or are there more efficient processing methods?

**Comment by Li-Z-Q** [comment]
## For Question 1:

> Should the algorithm determine data types and structurize all documents before processing each query?

Yes, our current approach is to structure all the documents.

> If preprocessing all documents isn't necessary, what's the optimal strategy for selecting query-relevant documents? Should document core content be the primary matching criteria?

This is a very valuable question, and we are also considering this matter. If the document repository is extremely large, it becomes necessary to perform some pre-filtering. One possible approach is to use methods like dense retrieval to initially filter documents based on their core content. However, we do not yet have a fully developed solution. Discussions are welcome!

## For Question 2:

We haven't worked with Excel files on such a large scale before, so we're not sure what the optimal solution would be. 
Intuitively, "treating it as a single large table" might not be the best approach. In another project's experiments, I observed that when the token count reaches around the 100K level, the quality of the model's generated content tends to degrade significantly. 
Therefore, I suspect that splitting the large table into multiple smaller tables, processing them individually, and then integrating the results might yield better outcomes.

**Comment by Z-ZHHH** [comment]
Thank you for your reply – it was very helpful.

I have some concerns about the computational complexity with structRAG versus vanilla RAG:

When we define $n$ as the query number, $N_L$ as LLM processing complexity, and $N_E$ as embedding processing complexity, we can see that structRAG has a complexity of $O(n N_L)$, while vanilla RAG has a complexity of $O(n N_E)$. Given Qwen2-72B, $N_L$ is significantly larger than $N_E$. Furthermore, structRAG's computational complexity increases much more rapidly as the number of queries grows.

IN my opinion, for industrial applications, this presents a significant challenge. When dealing with knowledge databases containing over 200K tokens, processing all documents for each query becomes computationally expensive and time-consuming. This makes the _latency_ and _resource requirements_ potentially prohibitive for practical use. 
From an academic perspective, the approach is innovative, and motivation about cognitive theory sounds great.
